### ISSUE TITLE
CLI Wellness content clarification

### ISSUE THREAD

**Issue by rbartelme** [hcwhosted/hcwhosted.github.io#26]
- Could we unify Mental Health Resources and Helplines in a single module?

- Could Physical selfceare and exercise be combined?

- What are patient resources? Could this be better defined?

- COVID-19 & Supporting Those Diagnosed… how does this APA link fit into more broad topics?

*Feel free to post responses to this, and we can finalize content mapping on the Wellness page. This way as new information comes in we can bin the links into broadly applicable categories*

**Comment by mgwall17** [comment]
BTW, the accordion cards are not functional for me, I held off on styling the wellness page in case we ended up not going with the accordion.
